import { emptyContact } from '../utils/toolbox'

// Mettre ces 2 dates null si vides
// Modif 2 date => = new Date("2019-02-26") par exemple
// Modif isClient en true ou false
// Mettre en chiffre (sans les "") => "hasBeenCalled": + "hasBeenSentEmailOrMeetUp"

const contactsLaurianeCampings_x10: Contact[] = [
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": true,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Port Pothiau",
        "businessPhone": " 04 94 66 39 66",
        "contactPhone": "",
        "contactEmail": "info@pothuau.com",
        "contactName": "Julie",
        "contactPosition": "Directrice",
        "businessAddress": "hyeres",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 3,
        "comments": "travailler en 2017 puis prestations toutes les semaines 2023",
        "dateOfFirstCall": new Date("2019-02-26")
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": true,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Capricorne 3*",
        "businessPhone": "04 94 66 40 94",
        "contactPhone": "",
        "contactEmail": "accueil@campingcapricorne.com",
        "contactName": "Nathalie",
        "contactPosition": "Directrice",
        "businessAddress": "Hyères",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 3,
        "comments": "2 prestations 2023",
        "dateOfFirstCall": new Date("2023-02-01")
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": true,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Camping le ceinturon",
        "businessPhone": "04 94 66 32 65",
        "contactPhone": "06 23 06 13 90",
        "contactEmail": "contact@ceinturon3.fr",
        "contactName": "Camille",
        "contactPosition": "décisionnaire",
        "businessAddress": "Hyères",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 3,
        "comments": "2 prestations 2023",
        "dateOfFirstCall": null
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": true,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Les palmiers 4*",
        "businessPhone": "04 94 66 39 66 / 06 25 18 48 35",
        "contactPhone": "",
        "contactEmail": "contact@camping-les-palmiers.fr",
        "contactName": "Husson",
        "contactPosition": "responsable annimation",
        "businessAddress": "hyeres",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 3,
        "comments": "4 prestations 2023",
        "dateOfFirstCall": new Date("2019-01-09")
    },    
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": false,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Camping Vert Gapeau",
        "businessPhone": "04 94 65 68 55",
        "contactPhone": "",
        "contactEmail": "camping@vertgapeau.com",
        "contactName": "Mr Roulot",
        "contactPosition": "dirigeant",
        "businessAddress": "hyeres",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 0,
        "comments": "",
        "dateOfFirstCall": new Date("2018-12-21")
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": false,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Camping l'Artaudois",
        "businessPhone": "04 94 21 72 61",
        "contactPhone": "",
        "contactEmail": "romain@artaudois.fr",
        "contactName": "Mr Romain",
        "contactPosition": "",
        "businessAddress": "le pradet",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 0,
        "comments": "pas possible 2023",
        "dateOfFirstCall": new Date("2023-02-01")
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": false,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Camping Saint Pierre Des Horts",
        "businessPhone": "06 07 76 31 05",
        "contactPhone": "",
        "contactEmail": "",
        "contactName": "",
        "contactPosition": "",
        "businessAddress": "hyeres",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 0,
        "comments": "impossible pas d'animation , que mobilhome",
        "dateOfFirstCall": new Date("2019-01-09")
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": false,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Les Bois de Mont Redon",
        "businessPhone": "04 94 66 24 50",
        "contactPhone": "",
        "contactEmail": "mont.redon2@gmail.com",
        "contactName": "Mr Audibert",
        "contactPosition": "dirigent",
        "businessAddress": "la crau",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 0,
        "comments": "mail envoyer au directeur- Pas aimable - revoir si l'an prochain il a changé ou changement de direction",
        "dateOfFirstCall": new Date("2023-12-04")
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": false,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Camping Clos Rose Marie",
        "businessPhone": "04 94 66 41 21    06 23 06 13 90",
        "contactPhone": "",
        "contactEmail": "",
        "contactName": "",
        "contactPosition": "",
        "businessAddress": "hyeres",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 0,
        "comments": "PAS INTERESSER PAS AIMABLE",
        "dateOfFirstCall": new Date("2019-12-09")
    },
    {
        ...emptyContact,
        "businessType": "Camping",
        "isClient": false,
        "dateOfNextCall": null,
        "logo": "",
        "businessName": "Camping Eurosurf campéole Hyères Gien",
        "businessPhone": "+33(0)4 94 58 90 16",
        "contactPhone": "",
        "contactEmail": "fpchantrein@campeole.com",
        "contactName": "Chantrein",
        "contactPosition": "Directeur",
        "businessAddress": "hyeres",
        "hasBeenCalled": 0,
        "hasBeenSentEmailOrMeetUp": 0,
        "comments": "PAS DE PISCINE",
        "dateOfFirstCall": null
    },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "INTERNATIONAL & SPA****",
    //     "businessPhone": " 04 94 58 23 59",
    //     "contactPhone": "",
    //     "contactEmail": "thierry.coulomb@wanadoo.fr",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "hyeres",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "JEAN LUC Y EST",
    //     "dateOfFirstCall": new Date("2018-01-09")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping La Tour Fondue",
    //     "businessPhone": "04 94 58 21 51",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "hyeres",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas de piscine",
    //     "dateOfFirstCall": new Date("2019-01-22")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Lou Pantaï",
    //     "businessPhone": "04 94 75 10 77",
    //     "contactPhone": "",
    //     "contactEmail": "contact@campingloupantai.com",
    //     "contactName": "Mr Demarais",
    //     "contactPosition": "Directi",
    //     "businessAddress": "le pradet",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "\"mail envoyer au directeur/pas interesser , bizar la facon dont il a répondu \"\"une sirene à l'état naturelle n'a rien a faire dans un camping\"",
    //     "dateOfFirstCall": new Date("2023-02-01")
    // },   
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Parc Valrose",
    //     "businessPhone": "04 94 66 81 36",
    //     "contactPhone": "",
    //     "contactEmail": "aurelie@parcvalrose.com",
    //     "contactName": "LA LONDE LES MAURES",
    //     "contactPosition": "directrice",
    //     "businessAddress": "Aurélie",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "valider si a bien recu le cata et si elle est intéressée, répondeur le 2 mai 2023",
    //     "dateOfFirstCall": new Date("2023-01-09")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "camping l'argentière",
    //     "businessPhone": "04 94 54 63 63",
    //     "contactPhone": "",
    //     "contactEmail": "contact@camping-argentiere.com",
    //     "contactName": "clementine",
    //     "contactPosition": "responsable anim",
    //     "businessAddress": "Cogolin",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas interesser pour 2023",
    //     "dateOfFirstCall": new Date("2023-02-16")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Domaine Marin",
    //     "businessPhone": "0494 43 22 95",
    //     "contactPhone": "",
    //     "contactEmail": "domainemarin@orange.fr",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Grimaud",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "donné flyer sur place + mail le 30 janvier 2023 , répondeur le 22 février",
    //     "dateOfFirstCall": new Date("2023-03-14")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Pachacaïd Capfun",
    //     "businessPhone": "04 94 55 70 80",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "camille",
    //     "contactPosition": "attaché de direction",
    //     "businessAddress": "",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas intéresser pour 2023",
    //     "dateOfFirstCall": new Date("2023-01-30")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "les tournels",
    //     "businessPhone": "",
    //     "contactPhone": " 06 03 59 19 40",
    //     "contactEmail": "",
    //     "contactName": "Charlotte",
    //     "contactPosition": "RESP ANIMATION",
    //     "businessAddress": "Ramatuelle",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "trop compliquer , car trop d'enfant dans la piscine",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": true,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "La brulade",
    //     "businessPhone": "04 94 66 86 28",
    //     "contactPhone": "614714555",
    //     "contactEmail": "amandine.calmettes@outlook.fr / elodiecalmettes@hotmail.fr",
    //     "contactName": "Elodie Calemettes",
    //     "contactPosition": "réponsable animation",
    //     "businessAddress": "La londe",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 3,
    //     "comments": "",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": " La Pabourette",
    //     "businessPhone": "04 94 66 80 92",
    //     "contactPhone": "",
    //     "contactEmail": "campinglapabourette@orange.fr",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "La londe",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "repondeur",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Pascalinette",
    //     "businessPhone": "04 94 66 82 72",
    //     "contactPhone": "",
    //     "contactEmail": "rreception@lapascalinette.fr",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas possible 2023",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": true,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "PRL Le Pinedou",
    //     "businessPhone": "04 94 65 68 55",
    //     "contactPhone": "",
    //     "contactEmail": "le.pinedou@orange.fr",
    //     "contactName": "",
    //     "contactPosition": "dirigente avec son maris",
    //     "businessAddress": "1110 Route de Maraval, 83260 La Crau",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 3,
    //     "comments": "2 prestations en 2017, 2 prestation en 2018, 1 en 2023",
    //     "dateOfFirstCall": null
    // },


    // ////////////   22 OK    ////////////////////////////////



    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Domaine de Verdagne",
    //     "businessPhone": "04 94 79 78 21",
    //     "contactPhone": "",
    //     "contactEmail": "direction@domaine-verdagne.com ",
    //     "contactName": "estelle",
    //     "contactPosition": "responsable anim",
    //     "businessAddress": "",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "prévois leur animations en mai",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Le Parc de Bormes - Vacances André Trigano",
    //     "businessPhone": "04 94 71 08 35",
    //     "contactPhone": "",
    //     "contactEmail": "parcdebormes@vacances-andretrigano.com",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "1042 Chem. du Niel, 83230 Bormes-les-Mimosas",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas de piscine, uniquement jeux d'eau",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Capfun la pinede ( à coté maison )",
    //     "businessPhone": "(0)4 94 79 09 80",
    //     "contactPhone": "",
    //     "contactEmail": "la-pinede@capfun.com",
    //     "contactName": "Solène Bruno",
    //     "contactPosition": "",
    //     "businessAddress": "Grimaud",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas interesser pour 2023",
    //     "dateOfFirstCall": new Date("2022-12-22")
    // },


    // ////////////   25 OK    ////////////////////////////////




    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "la toison d'or",
    //     "businessPhone": "04 94 43 26 95",
    //     "contactPhone": "",
    //     "contactEmail": "conciergerie@la-toison.com",
    //     "contactName": "MArtine Vella",
    //     "contactPosition": "",
    //     "businessAddress": "Ramatuelle",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": true,
    //     "dateOfNextCall": "07/12/2023",
    //     "logo": "",
    //     "businessName": "Le Domaine du Golfe de Saint Tropez",
    //     "businessPhone": "",
    //     "contactPhone": "",
    //     "contactEmail": "contact@golfe-saint-tropez.fr",
    //     "contactName": " Moine Sandra",
    //     "contactPosition": "",
    //     "businessAddress": "Grimaud",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 3,
    //     "comments": "pas possible pour 2023",
    //     "dateOfFirstCall": new Date("2022-03-12")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Paradis Domaine de Miremer",
    //     "businessPhone": "04 94 55 67 80 /",
    //     "contactPhone": "",
    //     "contactEmail": "contact@domainedemiremer.com",
    //     "contactName": "Mme Ollivier Sophie",
    //     "contactPosition": "",
    //     "businessAddress": "Grimaud",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas interesser pour 2023 , la directrice ne veut pas",
    //     "dateOfFirstCall": new Date("2022-09-20")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Les Naïades",
    //     "businessPhone": "",
    //     "contactPhone": "609532730",
    //     "contactEmail": "lesnaiades@marvilla-parks.com",
    //     "contactName": "Keiko Bellendorf",
    //     "contactPosition": "",
    //     "businessAddress": "Grimaud",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "mail envoyé au directeur",
    //     "dateOfFirstCall": new Date("2022-02-02")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Les prairies de la mer camping 5*",
    //     "businessPhone": "09 70 71 79 89",
    //     "contactPhone": "",
    //     "contactEmail": "jenna@riviera-villages.com  ",
    //     "contactName": "JennaDegnole",
    //     "contactPosition": "",
    //     "businessAddress": "GRIMAUD",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "bien recu, elle en a parler aux personnes de l'animation, reviennent vers moi si interesser. NE PAS RAPPELLER",
    //     "dateOfFirstCall": null
    // },





    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "le parc des chênes",
    //     "businessPhone": "(0) 4 94 55 10 30",
    //     "contactPhone": "",
    //     "contactEmail": "parcdeschenes@popinns.com",
    //     "contactName": "Mr Doose",
    //     "contactPosition": "",
    //     "businessAddress": "Croix valmer",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "ouvert 16h à 19h mail transmis au directeur, très rare qu'il fasse appel a des prestataires extérieurs",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": true,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "selection camping 4*",
    //     "businessPhone": "04 94 64 08 15",
    //     "contactPhone": "",
    //     "contactEmail": "camping-selection@wanadoo.fr   ",
    //     "contactName": " Anne Cavaille et Clara",
    //     "contactPosition": "",
    //     "businessAddress": "Croix valmer",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas possible en 2023",
    //     "dateOfFirstCall": new Date("2022-02-14")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping de la Baie",
    //     "businessPhone": "04 94 55 56 00",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "Mr Juillard",
    //     "contactPosition": "",
    //     "businessAddress": "Cavalaire",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "prends une entreprise extérieure qui font toutes les animations",
    //     "dateOfFirstCall": new Date("2022-02-07")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": " LE REVERDI Les Villages Clubs du Soleil  Village vacances",
    //     "businessPhone": "04 94 79 22 53",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "Mr Baukhlifa",
    //     "contactPosition": "",
    //     "businessAddress": "Plan de la tour",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas interesser pour 2023",
    //     "dateOfFirstCall": new Date("2019-01-21")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Cap Taillat",
    //     "businessPhone": "",
    //     "contactPhone": "",
    //     "contactEmail": "info@camping-captaillat.com",
    //     "contactName": "Isabelle legros",
    //     "contactPosition": "",
    //     "businessAddress": "RAmatuelle",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "ne font pas d'animation mais à quand meme prix mes coordonnés mail envoyer avec prix,",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Village vacances Ramatuelle",
    //     "businessPhone": "04 98 12 90 00",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": " Bruno",
    //     "contactPosition": "",
    //     "businessAddress": "RAmatuelle",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": true,
    //     "dateOfNextCall": "07/12/2023",
    //     "logo": "",
    //     "businessName": "La croix du sud 3*",
    //     "businessPhone": " 04 94 79 00 00",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "Marie Christine",
    //     "contactPosition": "",
    //     "businessAddress": "RAmatuelle",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 3,
    //     "comments": "PARTENARIAT tous les ans, fidéles",
    //     "dateOfFirstCall": null
    // },   
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Pierre et Vacance Grimaud",
    //     "businessPhone": "04 94 79 28 67 /         06 71 64 59 09",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "PAS ANIMATION",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": " la Rouillère",
    //     "businessPhone": "04 94 56 16 97",
    //     "contactPhone": "",
    //     "contactEmail": "pierre.campana0945@gmail.com",
    //     "contactName": "Pierre Campana",
    //     "contactPosition": "",
    //     "businessAddress": "Ramatuelle",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "pas d'animation piscine",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping les Mûres 4*",
    //     "businessPhone": "04 94 64 31 81",
    //     "contactPhone": "",
    //     "contactEmail": "camping.des.mures@gmail.com ",
    //     "contactName": "Mme Follin",
    //     "contactPosition": "",
    //     "businessAddress": "",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "PAS DE PISCINE",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping La Treille",
    //     "businessPhone": "04 94 64 10 87",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Cavalaire",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "  Ne font pas d'animation",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Cros De Mouton",
    //     "businessPhone": "04 94 15 20 72",
    //     "contactPhone": "",
    //     "contactEmail": "campingcrosdemouton@wanadoo.fr",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Cavalaire",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "\"font appel à une entreprise \"\"bleu blanc ciel\"\" qui s'occupe d'envoyé les animateurs sur place\"",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Lou Cabasson",
    //     "businessPhone": "04 94 56 08 43",
    //     "contactPhone": "",
    //     "contactEmail": "contact@campingloucabasson.com",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Bormes les mimosas",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Holiday Marina Resort",
    //     "businessPhone": " 04 94 71 53 39",
    //     "contactPhone": "",
    //     "contactEmail": "info@holiday-marina.com",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Grimaud",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "Plaquette envoyer, l'a recu mais pas interesser, camping pas familliale",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": " Tikayan Clau Mar Jo",
    //     "businessPhone": "04 94 71 03 28",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Bormes les mimosas",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "PAS ANIMATION",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "camping manjastre ***",
    //     "businessPhone": "494751077",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Bornes",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "AUCUNE ANIMATION",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Lou Pantaï",
    //     "businessPhone": "06 07 76 31 05",
    //     "contactPhone": "",
    //     "contactEmail": "contact@campingloupantai.com",
    //     "contactName": "Mr Demarais",
    //     "contactPosition": "",
    //     "businessAddress": "Le Pradet",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "\"pas interesser , bizar la facon dont il a répondu \"\"une sirene à l'état naturelle n'a rien a faire dans un camping\"",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Les Bois de Mont Redon",
    //     "businessPhone": "494451171",
    //     "contactPhone": "",
    //     "contactEmail": "mont.redon2@gmail.com",
    //     "contactName": "Mr Audibert",
    //     "contactPosition": "",
    //     "businessAddress": "La Crau",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "mail envoyer plaquette, pas aimable donc pas envie d'y aller",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Le Sellig",
    //     "businessPhone": "",
    //     "contactPhone": "",
    //     "contactEmail": "info@campingsellig.com",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Le Muy",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "recu mais pas intresser",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping de la vallée de Taradeau",
    //     "businessPhone": "04 94 45 12 08",
    //     "contactPhone": "",
    //     "contactEmail": "contact@campingdetaradeau.fr",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Vibaubant",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "trop cher pour presta en eau, souhaite en dessous de 200€, meme en bouche trou une semaine avant car fait ces animations à la semaine.",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Tikayan Les Cigales",
    //     "businessPhone": "04 94 45 10 04",
    //     "contactPhone": "",
    //     "contactEmail": "contact@les-cigales.com",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Le Muy",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "bien recu et transmi au bon service  pas voulu me donner de nom de personne pour l'objet,",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Tikayan La Prairie",
    //     "businessPhone": "04 94 68 18 27",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Le Muy",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "ne font pas appelle au entreprise extérieur",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping de la Foux",
    //     "businessPhone": "04 94 45 51 46",
    //     "contactPhone": "",
    //     "contactEmail": "",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Draguigant",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "45 min de grimaud en passant par st maxime",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping Les Aubrèdes",
    //     "businessPhone": "04 98 11 45 45",
    //     "contactPhone": "",
    //     "contactEmail": " aubredes@capfun.com",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Puget sur Argent",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Domaine de la Bergerie",
    //     "businessPhone": "04 11 32 90 00",
    //     "contactPhone": "",
    //     "contactEmail": "animation.cedrick@gmail.com",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "Vallée Du Fournel - 1960 Route Départementale 8 - Quartier Du Fournel - 83520 ROQUEBRUNE SUR ARGENS - France",
    //     "comments": "mail envoyé le 21 mars",
    //     "dateOfFirstCall": new Date("2023-03-17")
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "CAMPING   Riviera d'Azur",
    //     "businessPhone": "(0)4 94 17 62 49",
    //     "contactPhone": "",
    //     "contactEmail": " rivieradazur@sandaya.fr +33 (0)4 11 32 90 00 ligne direct : 049481015925",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "",
    //     "dateOfFirstCall": null
    // },
    // {
    //     ...emptyContact,
    //     "businessType": "Camping",
    //     "isClient": false,
    //     "dateOfNextCall": null,
    //     "logo": "",
    //     "businessName": "Camping de Saint-Aygulf Plage",
    //     "businessPhone": "",
    //     "contactPhone": "",
    //     "contactEmail": "info@campingdesaintaygulf.fr",
    //     "contactName": "",
    //     "contactPosition": "",
    //     "businessAddress": "",
    //     "hasBeenCalled": 0,
    //     "hasBeenSentEmailOrMeetUp": 0,
    //     "comments": "",
    //     "dateOfFirstCall": null
    // }
]

export default contactsLaurianeCampings_x10;
