// {
//     businessName : string,
//     businessPhone : string,
//     businessEmail : string,
//     businessAddress : string,
//     businessCity : string,
//     contactName : string,
//     contactPhone : string,
//     contactEmail : string,
//     contactPosition : string,
//     tag : string[],
//     interestGauge : number,
//     dateOfFirstCall : Date,
//     dateOfLastCall : Date,
//     dateOfNextCall : Date,
//     comments : string,
// }

const contacts = [
    {
        id: 1,
        businessName: "Pierre et vacances",
        activity: "", //"55.2",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "pierre&vacances@gmail.com",
        businessAddress: "1 rue de la paix Paris 75000",
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        tag: ["prospect", "évènementiel"],
        interestGauge: 5,
        dateOfFirstCall: new Date("2021-05-01"),
        dateOfLastCall: new Date("2022-05-01"),
        dateOfNextCall: new Date("2023-05-01"),
        comments: "Aucun commentaire",
    },
    {
        id: 2,
        businessName: "Camping Hyères",
        activity: "55.3",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix 83000 Hyères",
        businessCity: "Hyères",
        contactName: "Laurent Dupond2",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond2-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        tag: ["camping", "client"],
        interestGauge: 5,
        dateOfFirstCall: new Date("2023-05-01"),
        dateOfLastCall: new Date("2023-08-01"),
        dateOfNextCall: new Date("2023-11-01"),
        comments: "Aucun commentaire",
    },
    {
        id: 3,
        businessName: "Centre de plongée",
        activity: "93.12",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix St Tropez 83990 ",
        businessCity: "St Tropez",
        contactName: "Laurent Dupond3",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond3-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        tag: ["client", "partenaire"],
        interestGauge: 5,
        dateOfFirstCall: new Date("2023-10-11"),
        dateOfLastCall: new Date("2023-10-11"),
        dateOfNextCall: new Date("2023-11-11"),
        comments: "Aucun commentaire",
    },
    {
        id: 4,
        businessName: "Evénementiel",
        activity: "90.0",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix",
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        tag: ["client", "partenaire"],
        interestGauge: 5,
        dateOfFirstCall: new Date("2021-05-01"),
        dateOfLastCall: new Date("2021-05-01"),
        dateOfNextCall: new Date("2021-05-01"),
        comments: "Aucun commentaire",
    },
    {
        id: 5,
        businessName: "xxx",
        activity: "90.01Z",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix",
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        tag: ["client", "partenaire"],
        interestGauge: 5,
        dateOfFirstCall: new Date("2021-05-01"),
        dateOfLastCall: new Date("2021-05-01"),
        dateOfNextCall: new Date("2021-05-01"),
        comments: "Aucun commentaire",
    },
    // {
    //     id: 6,
    //     businessName: "Auchan",
    //     businessPhone: "06 xx xx xx xx",
    //     businessEmail: "xxx",
    //     businessAddress: "1 rue de la paix",
    //     businessCity: "Paris",
    //     contactName: "Laurent Dupond",
    //     contactPhone: "06 12 34 56 78",
    //     contactEmail: "dupond-pierre&vacances@gmail.com",
    //     contactPosition: "Directeur",
    //     tag: ["client", "partenaire"],
    //     interestGauge: 5,
    //     dateOfFirstCall: new Date("2021-05-01"),
    //     dateOfLastCall: new Date("2021-05-01"),
    //     dateOfNextCall: new Date("2021-05-01"),
    //     comments: "Aucun commentaire",
    // },
    // {
    //     id: 7,
    //     businessName: "Auchan",
    //     businessPhone: "06 xx xx xx xx",
    //     businessEmail: "xxx",
    //     businessAddress: "1 rue de la paix",
    //     businessCity: "Paris",
    //     contactName: "Laurent Dupond",
    //     contactPhone: "06 12 34 56 78",
    //     contactEmail: "dupond-pierre&vacances@gmail.com",
    //     contactPosition: "Directeur",
    //     tag: ["client", "partenaire"],
    //     interestGauge: 5,
    //     dateOfFirstCall: new Date("2021-05-01"),
    //     dateOfLastCall: new Date("2021-05-01"),
    //     dateOfNextCall: new Date("2021-05-01"),
    //     comments: "Aucun commentaire",
    // },
    // {
    //     id: 8,
    //     businessName: "Auchan",
    //     businessPhone: "06 xx xx xx xx",
    //     businessEmail: "xxx",
    //     businessAddress: "1 rue de la paix",
    //     businessCity: "Paris",
    //     contactName: "Laurent Dupond",
    //     contactPhone: "06 12 34 56 78",
    //     contactEmail: "dupond-pierre&vacances@gmail.com",
    //     contactPosition: "Directeur",
    //     tag: ["client", "partenaire"],
    //     interestGauge: 5,
    //     dateOfFirstCall: new Date("2021-05-01"),
    //     dateOfLastCall: new Date("2021-05-01"),
    //     dateOfNextCall: new Date("2021-05-01"),
    //     comments: "Aucun commentaire",
    // },
    // {
    //     id: 9,
    //     businessName: "Auchan",
    //     businessPhone: "06 xx xx xx xx",
    //     businessEmail: "xxx",
    //     businessAddress: "1 rue de la paix",
    //     businessCity: "Paris",
    //     contactName: "Laurent Dupond",
    //     contactPhone: "06 12 34 56 78",
    //     contactEmail: "dupond-pierre&vacances@gmail.com",
    //     contactPosition: "Directeur",
    //     tag: ["client", "partenaire"],
    //     interestGauge: 5,
    //     dateOfFirstCall: new Date("2021-05-01"),
    //     dateOfLastCall: new Date("2021-05-01"),
    //     dateOfNextCall: new Date("2021-05-01"),
    //     comments: "Aucun commentaire",
    // },
    // {
    //     id: 10,
    //     businessName: "Auchan",
    //     businessPhone: "06 xx xx xx xx",
    //     businessEmail: "xxx",
    //     businessAddress: "1 rue de la paix",
    //     businessCity: "Paris",
    //     contactName: "Laurent Dupond",
    //     contactPhone: "06 12 34 56 78",
    //     contactEmail: "dupond-pierre&vacances@gmail.com",
    //     contactPosition: "Directeur",
    //     tag: ["client", "partenaire"],
    //     interestGauge: 5,
    //     dateOfFirstCall: new Date("2021-05-01"),
    //     dateOfLastCall: new Date("2021-05-01"),
    //     dateOfNextCall: new Date("2021-05-01"),
    //     comments: "Aucun commentaire",
    // },
    // {
    //     id: 11,
    //     businessName: "Auchan",
    //     businessPhone: "06 xx xx xx xx",
    //     businessEmail: "xxx",
    //     businessAddress: "1 rue de la paix",
    //     businessCity: "Paris",
    //     contactName: "Laurent Dupond",
    //     contactPhone: "06 12 34 56 78",
    //     contactEmail: "dupond-pierre&vacances@gmail.com",
    //     contactPosition: "Directeur",
    //     tag: ["client", "partenaire"],
    //     interestGauge: 5,
    //     dateOfFirstCall: new Date("2021-05-01"),
    //     dateOfLastCall: new Date("2021-05-01"),
    //     dateOfNextCall: new Date("2021-05-01"),
    //     comments: "Aucun commentaire",
    // },  
];

export default contacts;
