// {
//     businessName : string,
//     businessPhone : string,
//     businessEmail : string,
//     businessAddress : string,
//     businessCity : string,
//     contactName : string,
//     contactPhone : string,
//     contactEmail : string,
//     contactPosition : string,
//     tag : string[],
//     interestGauge : number,
//     dateOfFirstCall : Date,
//     dateOfLastCall : Date,
//     dateOfNextCall : Date,
//     comments : string,
// }


const contacts : Contact[] = [
//const contacts = [
    {
        id: "1",
        // logo : "https://www.pierreetvacances.com/medias/sys_master/images/images/hf1/hf7/8805202177566.jpg",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Pierre et vacances",
        denominationUsuelleEtablissement : [],
        interestGauge: 10,
        businessActivity: "", //"55.2",
        businessAddress: "1 rue de la paix Paris 75000",
        businessWebsite : "https://www.pierreetvacances.com/fr",        
        businessPhone: "06 xx xx xx xx",
        businessEmail: "pierre&vacances@gmail.com",
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: false,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["prospect", "évènementiel"],
        dateOfFirstCall: new Date("2023-10-31T14:33"),        // Ou new Date(2021, 5, 1, 14, 30)  => !!! janvier = 0
        dateOfLastCall: new Date("2022-05-01"),
        dateOfNextCall: new Date("2023-10-31T14:33"),
        comments: "Ont l'air pas sympa  \n mais j'ai entendu qu'il fallait leur parler longtemps pour les mettre en confiance. S'en rappeler ! Car parfois il faut insister etc... j'écris pour avoir une longue phrase...",
    },
    {
        id: "2",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Camping Hyères",
        denominationUsuelleEtablissement : [],
        interestGauge: 7,
        businessActivity: "55.3",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix 83000 Hyères",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "Hyères",
        contactName: "Laurent Dupond2",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond2-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: true,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["camping", "client"],
        dateOfFirstCall: new Date("2023-05-01"),
        dateOfLastCall: new Date("2023-08-01"),
        dateOfNextCall: new Date("2023-10-31T14:33"),
        comments: "Aucun commentaire",

    },
    {
        id: "3",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Centre de plongée",
        denominationUsuelleEtablissement : [],
        interestGauge: 0,
        businessActivity: "93.12",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix St Tropez 83990 ",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "St Tropez",
        contactName: "Laurent Dupond3",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond3-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: true,
        hasBeenSentEmail: true,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["client", "partenaire"],
        dateOfFirstCall: new Date("2023-10-11"),
        dateOfLastCall: new Date("2023-10-11"),
        dateOfNextCall: new Date("2023-10-31"),
        comments: "Très gentils",
    },
    {
        id: "4",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Les Trésors de Lily",
        denominationUsuelleEtablissement : [],
        interestGauge: 2,
        businessActivity: "90.0",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: true,
        hasBeenSentEmail: true,
        hasReceivedEmail: true,
        fileSent: null,
        tag: ["client", "partenaire"],
        dateOfFirstCall: new Date("2021-05-01"),
        dateOfLastCall: new Date("2021-05-01"),
        dateOfNextCall: new Date("2021-05-01"),
        comments: "Aucun commentaire",
    },
    {
        id: "5",
        businessName: "xxx",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        denominationUsuelleEtablissement : [],
        interestGauge: 4,
        businessActivity: "90.01Z",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: false,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["client", "partenaire"],
        dateOfFirstCall: new Date("2021-05-01"),
        dateOfLastCall: new Date("2021-05-01"),
        dateOfNextCall: new Date("2021-05-01"),
        comments: "Aucun commentaire",
    },   
    {
        id: "6",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Camping Hyères",
        denominationUsuelleEtablissement : [],
        interestGauge: 6,
        businessActivity: "55.3",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix 83000 Hyères",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "Hyères",
        contactName: "Laurent Dupond2",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond2-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: false,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["camping", "client"],
        dateOfFirstCall: new Date("2023-05-01"),
        dateOfLastCall: new Date("2023-08-01"),
        dateOfNextCall: new Date("2023-11-01"),
        comments: "Aucun commentaire",
    },
    {
        id: "7",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Centre de plongée",
        denominationUsuelleEtablissement : [],
        interestGauge: 8,
        businessActivity: "93.12",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix St Tropez 83990 ",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "St Tropez",
        contactName: "Laurent Dupond3",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond3-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: false,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["client", "partenaire"],
        dateOfFirstCall: new Date("2023-10-11"),
        dateOfLastCall: new Date("2023-10-11"),
        dateOfNextCall: new Date("2023-11-11"),
        comments: "Aucun commentaire",
    },
    {
        id: "8",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Les Trésors de Lily",
        denominationUsuelleEtablissement : [],
        interestGauge: 10,
        businessActivity: "90.0",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: false,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["client", "partenaire"],
        dateOfFirstCall: new Date("2021-05-01"),
        dateOfLastCall: new Date("2021-05-01"),
        dateOfNextCall: new Date("2021-05-01"),
        comments: "Aucun commentaire",
    },
    {
        id: "9",
        businessName: "xxx",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        denominationUsuelleEtablissement : [],
        interestGauge: 9,
        businessActivity: "90.01Z",
        businessPhone: "06 xx xx xx xx",
        businessEmail: "xxx",
        businessAddress: "1 rue de la paix",
        businessWebsite : "https://www.pierreetvacances.com/fr", 
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: false,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["client", "partenaire"],
        dateOfFirstCall: new Date("2021-05-01"),
        dateOfLastCall: new Date("2021-05-01"),
        dateOfNextCall: new Date("2021-05-01"),
        comments: "Très gentils",
    },
    {
        id: "10",
        // logo : "https://www.pierreetvacances.com/medias/sys_master/images/images/hf1/hf7/8805202177566.jpg",
        logo : "https://logo.clearbit.com/pierreetvacances.com",
        businessName: "Pierre et vacances",
        denominationUsuelleEtablissement : [],
        interestGauge: 8,
        businessActivity: "", //"55.2",
        businessAddress: "1 rue de la paix Paris 75000",
        businessWebsite : "https://www.pierreetvacances.com/fr",        
        businessPhone: "06 xx xx xx xx",
        businessEmail: "pierre&vacances@gmail.com",
        businessCity: "Paris",
        contactName: "Laurent Dupond",
        contactPhone: "06 12 34 56 78",
        contactEmail: "dupond-pierre&vacances@gmail.com",
        contactPosition: "Directeur",
        hasBeenCalled: false,
        hasBeenSentEmail: false,
        hasReceivedEmail: false,
        fileSent: null,
        tag: ["prospect", "évènementiel"],
        dateOfFirstCall: new Date("2021-05-01"),        // Ou new Date(2021, 5, 1)
        dateOfLastCall: new Date("2022-05-01"),
        dateOfNextCall: new Date("2023-05-01"),
        comments: "On l'air pas sympa mais j'ai entendu qu'il fallait leur parler longtemps pour les mettre en confiance. S'en rappeler !",
    },





];

export default contacts;
